### ISSUE TITLE
Make button more responsive

### ISSUE THREAD

**Issue by Eeems** [rM-self-serve/webinterface-upload-button#1]
Currently, it doesn't flow with the rest of the content, so it doesn't look that great on higher resolution monitors.
![image](https://github.com/rM-self-serve/webinterface-upload-button/assets/1176979/cddfda81-4af4-477e-8f79-d3d25f0e1c71)
(I'm using darkreader, so ignore the dark colours).

**Comment by rM-self-serve** [comment]
No debate there. In the short term it is targeted at mobile use with intentions to replace the html with an improved javascript implementation, off of the root partition. This will also handle multiple file uploads and no longer redirect to the http response code.

**Comment by rM-self-serve** [comment]
Addressed in 0643ba1dfe052dc1c71687caf10a156776f98105
