### ISSUE TITLE
hbtn_elm is null

### ISSUE THREAD

**Issue by fkranhold** [rM-self-serve/webinterface-upload-button#5]
With Version 3.11.2.4, the script does not work any more; the js debugger of Firefox says the following:

```
Uncaught (in promise) TypeError: hbtn_elm is null
    init http://10.11.99.1/webinterface-upload-button.js:36
    async* http://10.11.99.1/webinterface-upload-button.js:155
```

**Comment by rM-self-serve** [comment]
Thanks for the report. I do not have access to that version yet but will take a look when I do. It seems they have been giving the web interface more attention lately.

**Comment by spencerpogo** [comment]
I managed to get it to work again. The page uses javascript now, so a mutation observer is needed to wait for it to render. Also, the download button doesn't show up until you click on a file, so we can't clone it anymore. Instead, I build the icon manually, which is a bit more jank. 
Here's the userscript I'm using: https://gist.github.com/Scoder12/3bb05946642fa788d3538598f99448a5

**Comment by rM-self-serve** [comment]
Thanks for the heads up! I hope everyone has sent messages to the company asking for an upload button. Its pretty ridiculous they are redesigning the web page but still haven't added that.

The newest version also has a new update mechanism so I'm waiting for the tooling around that to catch up.

I might ask you turn this into a pull request when I'm ready!

**Comment by spencerpogo** [comment]
Ok, just let me know. 

This script has been essential for me because I don't use the cloud services.

**Comment by rM-self-serve** [comment]
@Scoder12 Could you make a pull request? Looks solid and works all the way down to v2.10. Only has to be for the js file, I will do the rest.

Not sure if you saw but they added an import button in v3.12!

**Comment by spencerpogo** [comment]
Great to hear they finally added the button!
